name: 17-armor-stand-GUI-plugin-P2
version: '${version}'
main: minecraft.demo.armorstandguipluginp2.ArmorStandGUIPluginP2
api-version: 1.18
commands:
  armorstand:
    description: Create a armor stand.
    usage: /<command>
    aliases:
      - as