name: 54-tab-completion-with-commands
version: '${version}'
main: minecraft.demo.tabcompletionwithcommands.TabCompletionWithCommands
api-version: 1.18
commands:
  murder:
    description: Murder a fool