name: 18-armor-stand-GUI-plugin-P3
version: '${version}'
main: minecraft.demo.armorstandguipluginp3.ArmorStandGUIPluginP3
api-version: 1.18
commands:
  armorstand:
    description: Create a armor stand.
    usage: /<command>
    aliases:
      - as