name: TeleportBow
version: '${project.version}'
main: com.plugins.teleportbow.TeleportBow
api-version: 1.17
author: baioretto
commands:
  getTpBow:
    description: Teleport anywhere with a bow
    usage: /<command>
