name: CommandArguments
version: '${project.version}'
main: com.plugins.commandarguments.CommandArguments
api-version: 1.17
author: baioretto
commands:
  send:
    description: send a message to yourself.
  kill:
    description: Kill a target player.