name: 19-armor-stand-GUI-plugin-P4
version: '${version}'
main: minecraft.demo.armorstandguipluginp4.ArmorStandGUIPluginP4
api-version: 1.18
commands:
  armorstand:
    description: Create a armor stand.
    usage: /<command>
    aliases:
      - as