name: CustomCommands
version: '${project.version}'
main: com.plugins.customcommands.CustomCommands
api-version: 1.17
commands:
  die:
    description: An easy way to kill your self
    usage: /<command>
  god:
    description: Make you come invulnerable
    usage: /<command>
    aliases: [king, wtf]
  feed:
    description: Feed yourself
    usage: /<commnad>