name: VaultInventory
version: '${project.version}'
main: com.plugins.vaultinventory.VaultInventory
api-version: 1.17
author: baioretto
commands:
  vault:
    description: Open a vault.
    usage: /<command>